"""initial schema

Revision ID: ad68116c296a
Revises: 
Create Date: 2026-08-31 10:38:44.072564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # provides the portable GUID column type used below


# revision identifiers, used by Alembic.
revision: str = 'ad68116c296a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('asignado_a', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_estado', 'tickets', ['estado'], unique=False)
    op.create_index('ix_tickets_prioridad', 'tickets', ['prioridad'], unique=False)
    op.create_table('comments',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('ticket_id', app.types.GUID(), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_ticket_id'), 'comments', ['ticket_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('ticket_id', app.types.GUID(), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_comments_ticket_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_tickets_prioridad', table_name='tickets')
    op.drop_index('ix_tickets_estado', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
